### PR TITLE
[WIP] Testing

### PR DESCRIPTION
**Pull request by TomasVotruba**
Ref #45

### CODE REVIEW

**Comment by crazko** [comment]
This is not gonna help. My site is being generated into `dist` directory; also `generate` command is part of my [build `script`](https://github.com/crazko/romanvesely.com/blob/master/gulpfile.js#L77)

**Comment by TomasVotruba** [comment]
That's for local testing.

So test pass silently?

**Comment by crazko** [comment]
In my case `npm run build` run the same command. Or I don't get what you mean by local testing.

Anyway, in case of missing variable it outputs "OK":

ezgif com-video-to-gif

So I assume, that's not expected behavior.

**Comment by TomasVotruba** [comment]
> Or I don't get what you mean by local testing.

So I can open `localhost:8000` or something like that and see the website.

Basically step 4. here: https://github.com/pehapkari/pehapkari.cz

image

**Comment by crazko** [comment]
ah, its `npm start`

**Comment by TomasVotruba** [comment]
Could you add that to README so it's clear this is the one?

**Comment by crazko** [comment]
Well, it's there, defined under commands https://github.com/crazko/romanvesely.com/blob/master/README.md#use-it

**Comment by TomasVotruba** [comment]
I've read it but did't get it, thus this issue :D

**Comment by TomasVotruba** [comment]
I wan't to run 1 command to get it all. I don't know why 6 commands are needed just to get website running.

**Comment by crazko** [comment]
Nobody said all 6 of them are needed to run it 😉 Hopefully it's more clear now https://github.com/crazko/romanvesely.com/commit/16dbdf8f71b7e7709c6d7a3108a27ffc32e41339?diff=unified&short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by TomasVotruba** [comment]
I though I have to do. What would be point of having them there if I don't need them.

Better, thank you :+1:

**Comment by crazko** [comment]
I like to keep all important information in README. It's like a documentation for _future me_.

**Comment by TomasVotruba** [comment]
I see. I write README for users, since they read it more often than I and have no initial idea what is the project about.

**Pull request closed without merging**
