### PR TITLE
Upgrade Statie to 5.3

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by crazko** [comment]
Thanks man, I just need to test the whole site. I think anchors in the post headings have been removed.

markdown_headline_anchors => post_headline_linker_enabled

**Comment by TomasVotruba** [comment]
Yes. Add it on merge after you test the site, if that's not an issue

**Comment by crazko** [comment]
hmm, it is not working properly, there are parts of the layout that are missing.

**Comment by TomasVotruba** [comment]
What exactly?

**Comment by crazko** [comment]
Here https://github.com/crazko/romanvesely.com/blob/master/site/_layouts/post.latte

`{block content}` is not used, but the content of the post is here https://github.com/crazko/romanvesely.com/blob/master/site/_layouts/default.latte#L59 directly

But `{block meta}` and `{block scripts}` are both correctly in the output.

**Comment by crazko** [comment]
I've just tried to rename `{block content}` to `{block foo}` and it's working. So I assume that `$post['content']` and `{block content}` are fighting together.

**Comment by TomasVotruba** [comment]
Ah, that's the same issues as in statie.org. The post should be standalone template

**Comment by crazko** [comment]
Yeah, well, in that case I'll stick with the older version.

**Comment by TomasVotruba** [comment]
Do you want to go in depth yourself as in statie.org, which will take rather big amount of time, or can I create `post.latte` with includes as in statie.org?

**Comment by crazko** [comment]
Thanks, but I'd rather keep layout inheritance as it is now, so I'm fine with the older version of Statie now.

**Comment by TomasVotruba** [comment]
Understood :+1:

**Pull request closed without merging**
